name: Publish

on:
  push:
    tags:
      - 'v*'


jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: pypa/hatch@install
      - run: hatch build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
