name: Publish

on:
  push:


jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pypa/hatch@install
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
