name: Test

on:
  push:
  pull_request:


jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-13, macos-14, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/hatch@install
      - run: |
          hatch run test:run
          hatch run cov:combine
          { echo '## Test Coverage on ${{ matrix.runs-on }}'; echo '```'; hatch -q run cov:report; echo '```'; } >> "$GITHUB_STEP_SUMMARY"
        shell: bash
