name: Test

on:
  push:
  pull_request:


jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-13, maxos-14, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: pypa/hatch@install
      - runs: |
          hatch run test:run
          hatch run cov:combine
          echo '## Test Coverage on ${{ matrix.runs-on }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          hatch -q run cov:report >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        shell: bash
